### ISSUE TITLE
Replace Ansible module "synchronize" with "copy" for engines

### ISSUE THREAD

**Issue by derpadoo** [rackerlabs/scantron#247]
Having issues when having to ssh into a box as a low priv user and rsync files to /root for the engine.  Maybe just keep it simple and use the `copy` module?

```
- name: Copy engine files to server.
  copy:
    src: ../../../../engine
    dest: /root
    owner: root
    group: root
    mode: 0700
    backup: false
```
