### ISSUE TITLE
Generate random agent name in agent playbook instead of template

### ISSUE THREAD

**Issue by derpadoo** [rackerlabs/scantron#58]
```
- name: Generate random agent name.
  set_fact:
    random_agent_number: "{{ range(1, 999999) | random }}"
  when: utilize_static_api_token_across_agents
```

It currently resides in the template.  This will allow for better tracking later to determine the agent name for agent IPs if `utilize_static_api_token_across_agents` is `True`.
